name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build project
      run: pnpm run build
      
    - name: Create release package
      run: |
        mkdir -p release
        cp -r dist/* release/
        cp package.json release/
        cp README.md release/
        cd release
        tar -czf steam-achievements-downloader.tar.gz *
        zip -r steam-achievements-downloader.zip *
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release/steam-achievements-downloader.tar.gz
          release/steam-achievements-downloader.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 